name: Submit to App Stores

on:
  workflow_dispatch:  # Allows manual triggering
  release:
    types: [published]  # Triggers on new releases

jobs:
  submit_to_app_stores:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create What's New file
      run: |
        echo "New features in this release:" > whats_new.txt
        echo "- Feature 1" >> whats_new.txt
        echo "- Feature 2" >> whats_new.txt
        echo "- Bug fixes and performance improvements" >> whats_new.txt

    - name: Submit to App Stores
      uses: qhartman/app-store-submission@v0.1
      with:
        app_store_key_id: ${{ secrets.APP_STORE_KEY_ID }}
        app_store_issuer_id: ${{ secrets.APP_STORE_ISSUER_ID }}
        app_store_private_key: ${{ secrets.APP_STORE_PRIVATE_KEY }}
        app_store_app_id: ${{ secrets.APP_STORE_APP_ID }}
        google_play_json_key: ${{ secrets.GOOGLE_PLAY_JSON_KEY }}
        google_play_package_name: ${{ secrets.GOOGLE_PLAY_PACKAGE_NAME }}
        whats_new_file: 'whats_new.txt'

    - name: Clean up
      run: rm whats_new.txt