name: Submit to App Store

on:
  workflow_dispatch:

jobs:
  submit_to_app_store:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Submit to App Store
      uses: yourusername/app-store-submit-action@v1.0.0
      with:
        key_id: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
        issuer_id: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        private_key: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
        app_id: ${{ secrets.APP_STORE_APP_ID }}
        whats_new_file: 'path/to/whats_new.txt'
